Relax the wild dep
uutils/uucore pull request #8
Opened 2020-06-01 09:08 UTC by sylvestre

to make life easier of distro packagers.

2020-06-02 22:16 UTC, rivy commented
I submitted a [request](https://gitlab.com/kornelski/wild/-/merge_requests/3) to [`wild`](https://gitlab.com/kornelski/wild) requesting a minor change which would return v1.31.0 compatibility. We could relax the versioning if that request is merged.

2020-06-13 15:18 UTC, sylvestre commented
The new version of wild that @rivy improved has been published. We are good

2020-06-13 15:56 UTC, rivy requested changes
It should pass with the suggested dependency version.

After the change, I'll push it to *canary* to allow for CI testing.

2020-06-13 15:56 UTC, rivy commented on Cargo.toml
> +wild = "2.0"
```suggestion
wild = "2.0.4"
```

2020-06-13 16:40 UTC, rivy commented
Just FYI, `wild = "2.0.4"` is a fairly loose specification, only differing from `wild = "2.0"` by requiring greater than or equal to `2.0.4`.

`wild = "2.0.4"` == `wild = "^2.0.4"` == `wild = ">= 2.0.4, <3.0.0"` (per [cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)).

2020-06-13 17:33 UTC, merged